/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConocimientosRouteImport } from './routes/conocimientos'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as MemoriaRouteImport } from './routes/memoria'
import { Route as MiltRouteImport } from './routes/milt'
import { Route as PlantillasRouteImport } from './routes/plantillas'
import { Route as RecordatoriosRouteImport } from './routes/recordatorios'
import { Route as SolicitarAccesoRouteImport } from './routes/solicitar-acceso'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConocimientosRoute = ConocimientosRouteImport.update({
  id: '/conocimientos',
  path: '/conocimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaRoute = MemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const MiltRoute = MiltRouteImport.update({
  id: '/milt',
  path: '/milt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantillasRoute = PlantillasRouteImport.update({
  id: '/plantillas',
  path: '/plantillas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordatoriosRoute = RecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarAccesoRoute = SolicitarAccesoRouteImport.update({
  id: '/solicitar-acceso',
  path: '/solicitar-acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conocimientos': typeof ConocimientosRoute
  '/documentos': typeof DocumentosRoute
  '/favoritos': typeof FavoritosRoute
  '/herramientas': typeof HerramientasRoute
  '/memoria': typeof MemoriaRoute
  '/milt': typeof MiltRoute
  '/plantillas': typeof PlantillasRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/solicitar-acceso': typeof SolicitarAccesoRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conocimientos': typeof ConocimientosRoute
  '/documentos': typeof DocumentosRoute
  '/favoritos': typeof FavoritosRoute
  '/herramientas': typeof HerramientasRoute
  '/memoria': typeof MemoriaRoute
  '/milt': typeof MiltRoute
  '/plantillas': typeof PlantillasRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/solicitar-acceso': typeof SolicitarAccesoRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conocimientos': typeof ConocimientosRoute
  '/documentos': typeof DocumentosRoute
  '/favoritos': typeof FavoritosRoute
  '/herramientas': typeof HerramientasRoute
  '/memoria': typeof MemoriaRoute
  '/milt': typeof MiltRoute
  '/plantillas': typeof PlantillasRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/solicitar-acceso': typeof SolicitarAccesoRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conocimientos'
    | '/documentos'
    | '/favoritos'
    | '/herramientas'
    | '/memoria'
    | '/milt'
    | '/plantillas'
    | '/recordatorios'
    | '/solicitar-acceso'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/public/hooks/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/conocimientos'
    | '/documentos'
    | '/favoritos'
    | '/herramientas'
    | '/memoria'
    | '/milt'
    | '/plantillas'
    | '/recordatorios'
    | '/solicitar-acceso'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/public/hooks/reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conocimientos'
    | '/documentos'
    | '/favoritos'
    | '/herramientas'
    | '/memoria'
    | '/milt'
    | '/plantillas'
    | '/recordatorios'
    | '/solicitar-acceso'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/public/hooks/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConocimientosRoute: typeof ConocimientosRoute
  DocumentosRoute: typeof DocumentosRoute
  FavoritosRoute: typeof FavoritosRoute
  HerramientasRoute: typeof HerramientasRoute
  MemoriaRoute: typeof MemoriaRoute
  MiltRoute: typeof MiltRoute
  PlantillasRoute: typeof PlantillasRoute
  RecordatoriosRoute: typeof RecordatoriosRoute
  SolicitarAccesoRoute: typeof SolicitarAccesoRoute
  ApiChatRoute: typeof ApiChatRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conocimientos': {
      id: '/conocimientos'
      path: '/conocimientos'
      fullPath: '/conocimientos'
      preLoaderRoute: typeof ConocimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria': {
      id: '/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof MemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milt': {
      id: '/milt'
      path: '/milt'
      fullPath: '/milt'
      preLoaderRoute: typeof MiltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantillas': {
      id: '/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof PlantillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordatorios': {
      id: '/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof RecordatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar-acceso': {
      id: '/solicitar-acceso'
      path: '/solicitar-acceso'
      fullPath: '/solicitar-acceso'
      preLoaderRoute: typeof SolicitarAccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConocimientosRoute: ConocimientosRoute,
  DocumentosRoute: DocumentosRoute,
  FavoritosRoute: FavoritosRoute,
  HerramientasRoute: HerramientasRoute,
  MemoriaRoute: MemoriaRoute,
  MiltRoute: MiltRoute,
  PlantillasRoute: PlantillasRoute,
  RecordatoriosRoute: RecordatoriosRoute,
  SolicitarAccesoRoute: SolicitarAccesoRoute,
  ApiChatRoute: ApiChatRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
